# Generated by Django 3.2.5 on 2021-07-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('trace_request_eval', models.CharField(blank=True, default='', help_text='Trace a request, if the expression matches.\n                                   Example: "request.user.username==\'foo\'"\n                                   If empty, then every request gets traced.\n                                   For convenience request.get_full_path() is available in the variable "url".\n                                   Example2: "\'fooo\' in url"\n                                   Nested expressions are possible. \n                                   Example3: "request.user.username==\'foo\' and (\'bar\' in url or url.startswith(\'/blue\'))"\n                                   \n                                   This flexiblity has a draw-back. An evil staff-user could do "from foo.models import MyModel; MyModel.objects.all().delete()" or other fancy evil things.', max_length=1024)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('json_lines', models.TextField(default='', editable=False)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(default='')),
                ('url', models.URLField(default='')),
                ('http_status', models.CharField(default='', max_length=1024)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trace_cockpit.traceconfig')),
            ],
        ),
    ]
