# Generated by Django 3.2.5 on 2021-07-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_cockpit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
