# Generated by Django 3.2.5 on 2021-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_cockpit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracelog',
            name='http_status',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='traceconfig',
            name='trace_request_eval',
            field=models.CharField(blank=True, default='', help_text='Trace a request, if the expression matches.\n                                   Example: "request.user.username==\'foo\'"\n                                   If empty, then every request gets traced.\n                                   request.get_full_path() is available in the variable "url".\n                                   Example2: "\'fooo\' in url"\n                                   Nested expressions are possible. \n                                   Example3: "request.user.username==\'foo\' and (\'foo\' in url or url.startswith(\'/bar\')"', max_length=1024),
        ),
    ]
