# Generated by Django 3.2.5 on 2021-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_cockpit', '0002_traceconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracefilter',
            name='string',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
