# Generated by Django 3.2.5 on 2021-07-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trace_cockpit', '0003_tracefilter_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trace_cockpit.traceconfig')),
            ],
        ),
    ]
